development: &default
  port: 5433 
  adapter: postgresql
  database: avalanche_development
  encoding: utf8
  min_messages: warning
  pool: 2
  timeout: 5000

test:
  <<: *default
  database: avalanche_test
